slice = slice(8,-4)
website1 = ("https://google.com")
website2 = ("https://w3schools.com")

print("This program takes a sample website like this:")
print(website1)
print(website2)
print("And turns them into this")
print(website1[slice])
print(website2[slice])
print("This is just an example of what the program does. It isnt done yet and I will finish it when I get the chance to again...or feel like it.")
